// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: api/product_v1/product.proto

package product_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ProductV1Client is the client API for ProductV1 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProductV1Client interface {
	Fetch(ctx context.Context, in *URL, opts ...grpc.CallOption) (*emptypb.Empty, error)
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
}

type productV1Client struct {
	cc grpc.ClientConnInterface
}

func NewProductV1Client(cc grpc.ClientConnInterface) ProductV1Client {
	return &productV1Client{cc}
}

func (c *productV1Client) Fetch(ctx context.Context, in *URL, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/product_v1.ProductV1/Fetch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productV1Client) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, "/product_v1.ProductV1/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductV1Server is the server API for ProductV1 service.
// All implementations must embed UnimplementedProductV1Server
// for forward compatibility
type ProductV1Server interface {
	Fetch(context.Context, *URL) (*emptypb.Empty, error)
	List(context.Context, *ListRequest) (*ListResponse, error)
	mustEmbedUnimplementedProductV1Server()
}

// UnimplementedProductV1Server must be embedded to have forward compatible implementations.
type UnimplementedProductV1Server struct {
}

func (UnimplementedProductV1Server) Fetch(context.Context, *URL) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Fetch not implemented")
}
func (UnimplementedProductV1Server) List(context.Context, *ListRequest) (*ListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedProductV1Server) mustEmbedUnimplementedProductV1Server() {}

// UnsafeProductV1Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductV1Server will
// result in compilation errors.
type UnsafeProductV1Server interface {
	mustEmbedUnimplementedProductV1Server()
}

func RegisterProductV1Server(s grpc.ServiceRegistrar, srv ProductV1Server) {
	s.RegisterService(&ProductV1_ServiceDesc, srv)
}

func _ProductV1_Fetch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(URL)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductV1Server).Fetch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product_v1.ProductV1/Fetch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductV1Server).Fetch(ctx, req.(*URL))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductV1_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductV1Server).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product_v1.ProductV1/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductV1Server).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProductV1_ServiceDesc is the grpc.ServiceDesc for ProductV1 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProductV1_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "product_v1.ProductV1",
	HandlerType: (*ProductV1Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Fetch",
			Handler:    _ProductV1_Fetch_Handler,
		},
		{
			MethodName: "List",
			Handler:    _ProductV1_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/product_v1/product.proto",
}
